### ISSUE TITLE
Regex optimization possible - No space between quotations

### ISSUE THREAD

**Issue by CharlieBaird** [hawolt/poe-regex#71]
**Describe the bug**
Regex generator can save a character by removing the space between consecutive quotations.

**To Reproduce**
Make a regex with both a quant filter and a mod filter.

Original regex: `"!o s|s ref|0 s|or e|xa|wak|rs f" "m q.*1[4-9].%"`
New regex: `"!o s|s ref|0 s|or e|xa|wak|rs f""m q.*1[4-9].%"`

**Expected behavior**
Regex generator should remove the extra space to save an additional character.

**Additional context**
Thanks :)

**Comment by hawolt** [comment]
havent been active in a while, should go live in a bit!
